# Generated by Django 5.2.17 on 2026-09-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Toll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TripSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('origin_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('origin_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('destination_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('destination_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('fuel_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('average_speed_kmh', models.DecimalField(decimal_places=2, max_digits=6)),
                ('round_trip', models.BooleanField(default=False)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('duration_minutes', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fuel_liters', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fuel_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('toll_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('route_geometry', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('fuel_type', models.CharField(choices=[('gasoline', 'Gasolina'), ('ethanol', 'Etanol'), ('diesel', 'Diesel'), ('flex', 'Flex')], max_length=20)),
                ('consumption_km_per_liter', models.DecimalField(decimal_places=2, max_digits=6)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
